# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Scan Build for Unit testing"
  lane :run_build_test do
    scan(
      project: "Trial-Ci.xcodeproj",
      code_coverage: true,
      output_directory: "test_output/Trial-CiTest",
      scheme: "Trial-CiTest",
      clean: false,
      device: "iPhone 8 Plus",
      result_bundle: true
    )
  end

  xcresult_path = "test_output/Trial-CiTest/Trial-Ci.xcresult"

  desc "Code Coverage Report"
  lane :xcov_reposrt do
    xcov(
      project: "Trial-Ci.xcodeproj",
      scheme: "Trial-CiTest",
      xccov_file_direct_path: xcresult_path,
      output_directory: "test_output/Trial-CiTest/coverage",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "Notif to slack"
  lane :start_slack do
    slack(
      message: "Start UnitTest :rocket:",
      channel: "#jenkins-ios",
      payload: {"🗓 Build Date" => Time.new.to_s},
      default_payloads: [:git_branch, :last_git_commit, :git_author, :last_git_commit_hash],
      icon_url: "https://upload-icon.s3.us-east-2.amazonaws.com/uploads/icons/png/17080514251536298179-512.png",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end
